// Generated by CoffeeScript 1.8.0
(function() {
  var api;

  console.log('Starting apiVCR in record mode');

  console.log('');

  console.log('      ᕙ༼ ,,ԾܫԾ,, ༽ᕗ        ');

  console.log('');

  api = process.argv[2];

  if (!api || api === '') {
    console.warn("You must specify an api server to record: `node record.js http://api.magicalsailboat.com`");
    return 1;
  }

  require('./src/server.js').record(api);

}).call(this);
