// Generated by CoffeeScript 1.8.0
(function() {
  var server;

  console.log('Starting apiVCR in serve mode');

  console.log('');

  console.log('     (つ -‘ _ ‘- )つ        ');

  console.log('');

  server = require('./src/server.js');

  server.start();

}).call(this);
