// Generated by CoffeeScript 1.8.0
(function() {
  console.log('Starting apiVCR in serve mode');

  console.log('');

  console.log('     (つ -‘ _ ‘- )つ        ');

  console.log('');

  require('./src/server.js').start();

}).call(this);
