// Generated by CoffeeScript 1.8.0
(function() {
  var apiUrl, config, minimist, options, server, url;

  server = require('./src/server');

  minimist = require('minimist');

  url = require('url');

  config = require('./src/config');

  console.log('');

  console.log('apiVCR Starting');

  console.log('---------------');

  options = minimist(process.argv.slice(2));

  if (options.data) {
    config.rootPath = options.data;
  }

  console.log("Using data directory: `" + config.rootPath + "`");

  if (options.record) {
    apiUrl = url.parse(options.record);
    if (apiUrl.hostname) {
      config.api = apiUrl;
      server.record();
    } else {
      console.warn("Need to specify a valid url if you want to record: `node start.js --record=api.magicalsailboat.com`");
      console.warn("Your `record` option parsed to this url object: ", apiUrl);
      return 61;
    }
    if (config.api.port) {
      config.port = config.api.port;
    }
  }

  if (options.port) {
    config.port = options.port;
  }

  server.start();

}).call(this);
