// Generated by CoffeeScript 1.8.0
(function() {
  var createWatcher, http, https;

  http = require('http');

  https = require('https');

  createWatcher = function(api) {
    var host, port;
    host = api.split(':')[0];
    port = api.split(':')[1];
    console.log("constructing a watcher for api: `" + host + ":" + port + "`");
    return function(req, res, next) {
      var apiReq, onApiErr, onApiResponse;
      console.log("Proxying request: ", req.path);
      onApiResponse = function(res) {
        console.log("Got response from API server");
        console.log({
          status: res.statusCode,
          headers: JSON.stringify(res.headers)
        });
        res.setEncoding('utf8');
        res.on('data', function(chunk) {
          return console.log('BODY: ' + chunk);
        });
        return next();
      };
      onApiErr = function(err) {
        console.warn('problem with API request: ' + err.message);
        return next();
      };
      apiReq = http.get("" + req.protocol + "://" + host + ":" + port + req.path, onApiResponse);
      return apiReq.on('error', onApiErr);
    };
  };

  module.exports = {
    createWatcher: createWatcher
  };

}).call(this);
