// Generated by CoffeeScript 1.8.0
(function() {
  var METHODS, config, dataStore, fileScanner, fs, get, path, pathToFilename, save;

  fs = require('fs-extra');

  config = require('./config');

  fileScanner = require('./fileScanner');

  path = require('path');

  pathToFilename = function(apiPath) {
    return config.filePath + apiPath + '.json';
  };

  get = function(req, res, next) {
    var file, fileCallback;
    file = pathToFilename(req.path);
    fileCallback = function(err, data) {
      var sibling;
      if ((err != null ? err.code : void 0) === 'ENOENT' && config.sameSameSiblings) {
        console.log("Didn't find " + req.path + ". Looking for similar siblings...");
        sibling = fileScanner.getSiblingName(file);
        if (sibling) {
          console.log("Found a sibling. Returning `" + (path.basename(sibling)) + "`");
          return fs.readJson(sibling, fileCallback);
        }
      } else if ((err != null ? err.code : void 0) === 'ENOENT') {
        console.log("File not found: " + file);
        return next();
      } else if (err) {
        console.log("Unhandled error", {
          err: err,
          data: data
        });
        return next();
      } else {
        res.send(data);
        return next();
      }
    };
    return fs.readJson(file, fileCallback);
  };

  save = function(req, data) {
    var filename;
    filename = pathToFilename(req.path);
    return fs.outputJson(filename, data, function(err) {
      if (err) {
        return console.log("Couldn't write file `" + filename + "`", err);
      } else {
        return console.log("Wrote file: `" + filename + "`");
      }
    });
  };

  METHODS = {
    GET: get,
    POST: function() {
      return console.warn("dataStore.POST not yet supported", arguments);
    },
    PUT: function() {
      return console.warn("dataStore.PUT not yet supported", arguments);
    },
    DELETE: function() {
      return console.warn("dataStore.DELETE not yet supported", arguments);
    }
  };

  dataStore = {
    save: save,
    fetchDataForRequest: function(req) {
      console.log("Request received: " + req.method + " " + req.path);
      return METHODS[req.method].apply(this, arguments);
    }
  };

  module.exports = dataStore;

}).call(this);
