// Generated by CoffeeScript 1.8.0
(function() {
  var config, dataStore, fs, pathToFilename, readJsonFile, save;

  fs = require('fs-extra');

  config = require('./config');

  pathToFilename = function(path) {
    var filename;
    return filename = config.filePath + path + '.json';
  };

  readJsonFile = function(file) {
    var contents;
    console.log("dataStore readJsonFile()", file);
    contents = fs.readFileSync(file, {
      encoding: 'utf8'
    });
    return JSON.parse(contents);
  };

  save = function(req, data) {
    var filename;
    filename = pathToFilename(req.path);
    return fs.outputJson(filename, data, function(err) {
      if (err) {
        return console.log("Couldn't write file `" + filename + "`", err);
      } else {
        return console.log("Wrote file: `" + filename + "`");
      }
    });
  };

  dataStore = {
    GET: function(path) {
      return fs.readJsonSync(pathToFilename(path));
    },
    POST: function() {
      return console.log("dataStore.POST not yet supported", arguments);
    },
    PUT: function() {
      return console.log("dataStore.PUT not yet supported", arguments);
    },
    DELETE: function() {
      return console.log("dataStore.DELETE not yet supported", arguments);
    },
    save: save,
    fetchDataForRequest: function(req, res, next) {
      var data;
      console.log("Request received: " + req.method + " " + req.path);
      data = dataStore[req.method](req.path);
      if (data) {
        res.send(data);
      }
      return next();
    }
  };

  module.exports = dataStore;

}).call(this);
