// Generated by CoffeeScript 1.8.0
(function() {
  var config, fs, jsonFiles, readFiles;

  fs = require('fs');

  config = require('./config');

  jsonFiles = void 0;

  readFiles = function(path) {
    var contents, file, fullPath, _i, _len;
    path = path || config.rootPath;
    try {
      contents = fs.readdirSync(path);
    } catch (_error) {
      console.warn("`" + path + "` is not a folder");
      return;
    }
    for (_i = 0, _len = contents.length; _i < _len; _i++) {
      file = contents[_i];
      fullPath = "" + path + "/" + file;
      if (file.indexOf('.json') >= 0) {
        jsonFiles.push(fullPath);
      } else {
        readFiles(fullPath);
      }
    }
    return jsonFiles;
  };

  module.exports = {
    get: function() {
      jsonFiles = [];
      return readFiles();
    }
  };

}).call(this);
