// Generated by CoffeeScript 1.8.0

/*
  Stateless utility methods for accessing api-vcr files.
 */

(function() {
  var config, count, fs, getSiblingName, path, readFiles;

  fs = require('fs');

  config = require('./config');

  path = require('path');

  readFiles = function(filePath, jsonFiles) {
    var contents, file, fullPath, _i, _len;
    filePath = filePath || config.rootPath;
    jsonFiles = jsonFiles || [];
    if (config.ignore.indexOf(path.basename(filePath)) !== -1) {
      return;
    }
    try {
      contents = fs.readdirSync(filePath);
    } catch (_error) {
      console.log("`" + filePath + "` is not a folder, skipping");
      return;
    }
    for (_i = 0, _len = contents.length; _i < _len; _i++) {
      file = contents[_i];
      fullPath = "" + filePath + "/" + file;
      if (file.indexOf('.json') >= 0) {
        jsonFiles.push(fullPath);
      } else {
        readFiles(fullPath, jsonFiles);
      }
    }
    return jsonFiles;
  };

  getSiblingName = function(filename) {
    var dirContents;
    dirContents = readFiles(path.dirname(filename));
    return dirContents[0];
  };

  count = function() {
    count = readFiles().length;
    if (count === 0) {
      console.log("No JSON files found in `" + config.rootPath + "`");
      if (config.isRecording) {
        return console.log("Good thing you're recording");
      } else {
        return console.log("You should probably add some or run in `--record` mode first");
      }
    } else if (count === 1) {
      return console.log("Only found one file. What is this, don't trust me yet?");
    } else {
      return console.log("Found " + count + " JSON files. You're ready to jam.");
    }
  };

  module.exports = {
    count: count,
    getSiblingName: getSiblingName,
    get: readFiles
  };

}).call(this);
